/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZapomnialemHaslaRouteImport } from './routes/zapomnialem-hasla'
import { Route as ZajeciaRouteImport } from './routes/zajecia'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetHaslaRouteImport } from './routes/reset-hasla'
import { Route as RejestracjaRouteImport } from './routes/rejestracja'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as GrafikRouteImport } from './routes/grafik'
import { Route as CennikRouteImport } from './routes/cennik'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatnoscStatusRouteImport } from './routes/platnosc.status'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedMojeRezerwacjeRouteImport } from './routes/_authenticated/moje-rezerwacje'
import { Route as AuthenticatedKontoRouteImport } from './routes/_authenticated/konto'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicP24WebhookRouteImport } from './routes/api/public/p24/webhook'
import { Route as ApiPublicHooksProcessRemindersRouteImport } from './routes/api/public/hooks/process-reminders'

const ZapomnialemHaslaRoute = ZapomnialemHaslaRouteImport.update({
  id: '/zapomnialem-hasla',
  path: '/zapomnialem-hasla',
  getParentRoute: () => rootRouteImport,
} as any)
const ZajeciaRoute = ZajeciaRouteImport.update({
  id: '/zajecia',
  path: '/zajecia',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetHaslaRoute = ResetHaslaRouteImport.update({
  id: '/reset-hasla',
  path: '/reset-hasla',
  getParentRoute: () => rootRouteImport,
} as any)
const RejestracjaRoute = RejestracjaRouteImport.update({
  id: '/rejestracja',
  path: '/rejestracja',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const GrafikRoute = GrafikRouteImport.update({
  id: '/grafik',
  path: '/grafik',
  getParentRoute: () => rootRouteImport,
} as any)
const CennikRoute = CennikRouteImport.update({
  id: '/cennik',
  path: '/cennik',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatnoscStatusRoute = PlatnoscStatusRouteImport.update({
  id: '/platnosc/status',
  path: '/platnosc/status',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMojeRezerwacjeRoute =
  AuthenticatedMojeRezerwacjeRouteImport.update({
    id: '/moje-rezerwacje',
    path: '/moje-rezerwacje',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKontoRoute = AuthenticatedKontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicP24WebhookRoute = ApiPublicP24WebhookRouteImport.update({
  id: '/api/public/p24/webhook',
  path: '/api/public/p24/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessRemindersRoute =
  ApiPublicHooksProcessRemindersRouteImport.update({
    id: '/api/public/hooks/process-reminders',
    path: '/api/public/hooks/process-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/grafik': typeof GrafikRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/regulamin': typeof RegulaminRoute
  '/rejestracja': typeof RejestracjaRoute
  '/reset-hasla': typeof ResetHaslaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/zajecia': typeof ZajeciaRoute
  '/zapomnialem-hasla': typeof ZapomnialemHaslaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/moje-rezerwacje': typeof AuthenticatedMojeRezerwacjeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/platnosc/status': typeof PlatnoscStatusRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
  '/api/public/p24/webhook': typeof ApiPublicP24WebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/grafik': typeof GrafikRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/regulamin': typeof RegulaminRoute
  '/rejestracja': typeof RejestracjaRoute
  '/reset-hasla': typeof ResetHaslaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/zajecia': typeof ZajeciaRoute
  '/zapomnialem-hasla': typeof ZapomnialemHaslaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/moje-rezerwacje': typeof AuthenticatedMojeRezerwacjeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/platnosc/status': typeof PlatnoscStatusRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
  '/api/public/p24/webhook': typeof ApiPublicP24WebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cennik': typeof CennikRoute
  '/grafik': typeof GrafikRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/regulamin': typeof RegulaminRoute
  '/rejestracja': typeof RejestracjaRoute
  '/reset-hasla': typeof ResetHaslaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/zajecia': typeof ZajeciaRoute
  '/zapomnialem-hasla': typeof ZapomnialemHaslaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/konto': typeof AuthenticatedKontoRoute
  '/_authenticated/moje-rezerwacje': typeof AuthenticatedMojeRezerwacjeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/platnosc/status': typeof PlatnoscStatusRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
  '/api/public/p24/webhook': typeof ApiPublicP24WebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cennik'
    | '/grafik'
    | '/kontakt'
    | '/login'
    | '/polityka-prywatnosci'
    | '/regulamin'
    | '/rejestracja'
    | '/reset-hasla'
    | '/sitemap.xml'
    | '/studio'
    | '/zajecia'
    | '/zapomnialem-hasla'
    | '/admin'
    | '/konto'
    | '/moje-rezerwacje'
    | '/email/unsubscribe'
    | '/platnosc/status'
    | '/api/public/bootstrap-admin'
    | '/lovable/email/suppression'
    | '/api/public/hooks/process-reminders'
    | '/api/public/p24/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cennik'
    | '/grafik'
    | '/kontakt'
    | '/login'
    | '/polityka-prywatnosci'
    | '/regulamin'
    | '/rejestracja'
    | '/reset-hasla'
    | '/sitemap.xml'
    | '/studio'
    | '/zajecia'
    | '/zapomnialem-hasla'
    | '/admin'
    | '/konto'
    | '/moje-rezerwacje'
    | '/email/unsubscribe'
    | '/platnosc/status'
    | '/api/public/bootstrap-admin'
    | '/lovable/email/suppression'
    | '/api/public/hooks/process-reminders'
    | '/api/public/p24/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cennik'
    | '/grafik'
    | '/kontakt'
    | '/login'
    | '/polityka-prywatnosci'
    | '/regulamin'
    | '/rejestracja'
    | '/reset-hasla'
    | '/sitemap.xml'
    | '/studio'
    | '/zajecia'
    | '/zapomnialem-hasla'
    | '/_authenticated/admin'
    | '/_authenticated/konto'
    | '/_authenticated/moje-rezerwacje'
    | '/email/unsubscribe'
    | '/platnosc/status'
    | '/api/public/bootstrap-admin'
    | '/lovable/email/suppression'
    | '/api/public/hooks/process-reminders'
    | '/api/public/p24/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CennikRoute: typeof CennikRoute
  GrafikRoute: typeof GrafikRoute
  KontaktRoute: typeof KontaktRoute
  LoginRoute: typeof LoginRoute
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  RegulaminRoute: typeof RegulaminRoute
  RejestracjaRoute: typeof RejestracjaRoute
  ResetHaslaRoute: typeof ResetHaslaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  ZajeciaRoute: typeof ZajeciaRoute
  ZapomnialemHaslaRoute: typeof ZapomnialemHaslaRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PlatnoscStatusRoute: typeof PlatnoscStatusRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksProcessRemindersRoute: typeof ApiPublicHooksProcessRemindersRoute
  ApiPublicP24WebhookRoute: typeof ApiPublicP24WebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zapomnialem-hasla': {
      id: '/zapomnialem-hasla'
      path: '/zapomnialem-hasla'
      fullPath: '/zapomnialem-hasla'
      preLoaderRoute: typeof ZapomnialemHaslaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zajecia': {
      id: '/zajecia'
      path: '/zajecia'
      fullPath: '/zajecia'
      preLoaderRoute: typeof ZajeciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-hasla': {
      id: '/reset-hasla'
      path: '/reset-hasla'
      fullPath: '/reset-hasla'
      preLoaderRoute: typeof ResetHaslaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejestracja': {
      id: '/rejestracja'
      path: '/rejestracja'
      fullPath: '/rejestracja'
      preLoaderRoute: typeof RejestracjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grafik': {
      id: '/grafik'
      path: '/grafik'
      fullPath: '/grafik'
      preLoaderRoute: typeof GrafikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cennik': {
      id: '/cennik'
      path: '/cennik'
      fullPath: '/cennik'
      preLoaderRoute: typeof CennikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platnosc/status': {
      id: '/platnosc/status'
      path: '/platnosc/status'
      fullPath: '/platnosc/status'
      preLoaderRoute: typeof PlatnoscStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/moje-rezerwacje': {
      id: '/_authenticated/moje-rezerwacje'
      path: '/moje-rezerwacje'
      fullPath: '/moje-rezerwacje'
      preLoaderRoute: typeof AuthenticatedMojeRezerwacjeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/konto': {
      id: '/_authenticated/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof AuthenticatedKontoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/p24/webhook': {
      id: '/api/public/p24/webhook'
      path: '/api/public/p24/webhook'
      fullPath: '/api/public/p24/webhook'
      preLoaderRoute: typeof ApiPublicP24WebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-reminders': {
      id: '/api/public/hooks/process-reminders'
      path: '/api/public/hooks/process-reminders'
      fullPath: '/api/public/hooks/process-reminders'
      preLoaderRoute: typeof ApiPublicHooksProcessRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedKontoRoute: typeof AuthenticatedKontoRoute
  AuthenticatedMojeRezerwacjeRoute: typeof AuthenticatedMojeRezerwacjeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedKontoRoute: AuthenticatedKontoRoute,
  AuthenticatedMojeRezerwacjeRoute: AuthenticatedMojeRezerwacjeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CennikRoute: CennikRoute,
  GrafikRoute: GrafikRoute,
  KontaktRoute: KontaktRoute,
  LoginRoute: LoginRoute,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  RegulaminRoute: RegulaminRoute,
  RejestracjaRoute: RejestracjaRoute,
  ResetHaslaRoute: ResetHaslaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  ZajeciaRoute: ZajeciaRoute,
  ZapomnialemHaslaRoute: ZapomnialemHaslaRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PlatnoscStatusRoute: PlatnoscStatusRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksProcessRemindersRoute: ApiPublicHooksProcessRemindersRoute,
  ApiPublicP24WebhookRoute: ApiPublicP24WebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
