/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RejestracjaRouteImport } from './routes/rejestracja'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GrafikRouteImport } from './routes/grafik'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMojeRezerwacjeRouteImport } from './routes/_authenticated/moje-rezerwacje'
import { Route as AuthenticatedKontoRouteImport } from './routes/_authenticated/konto'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicHooksProcessRemindersRouteImport } from './routes/api/public/hooks/process-reminders'

const RejestracjaRoute = RejestracjaRouteImport.update({
  id: '/rejestracja',
  path: '/rejestracja',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GrafikRoute = GrafikRouteImport.update({
  id: '/grafik',
  path: '/grafik',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMojeRezerwacjeRoute =
  AuthenticatedMojeRezerwacjeRouteImport.update({
    id: '/moje-rezerwacje',
    path: '/moje-rezerwacje',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKontoRoute = AuthenticatedKontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksProcessRemindersRoute =
  ApiPublicHooksProcessRemindersRouteImport.update({
    id: '/api/public/hooks/process-reminders',
    path: '/api/public/hooks/process-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grafik': typeof GrafikRoute
  '/login': typeof LoginRoute
  '/rejestracja': typeof RejestracjaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/moje-rezerwacje': typeof AuthenticatedMojeRezerwacjeRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grafik': typeof GrafikRoute
  '/login': typeof LoginRoute
  '/rejestracja': typeof RejestracjaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/moje-rezerwacje': typeof AuthenticatedMojeRezerwacjeRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/grafik': typeof GrafikRoute
  '/login': typeof LoginRoute
  '/rejestracja': typeof RejestracjaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/konto': typeof AuthenticatedKontoRoute
  '/_authenticated/moje-rezerwacje': typeof AuthenticatedMojeRezerwacjeRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/grafik'
    | '/login'
    | '/rejestracja'
    | '/admin'
    | '/konto'
    | '/moje-rezerwacje'
    | '/api/public/hooks/process-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/grafik'
    | '/login'
    | '/rejestracja'
    | '/admin'
    | '/konto'
    | '/moje-rezerwacje'
    | '/api/public/hooks/process-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/grafik'
    | '/login'
    | '/rejestracja'
    | '/_authenticated/admin'
    | '/_authenticated/konto'
    | '/_authenticated/moje-rezerwacje'
    | '/api/public/hooks/process-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GrafikRoute: typeof GrafikRoute
  LoginRoute: typeof LoginRoute
  RejestracjaRoute: typeof RejestracjaRoute
  ApiPublicHooksProcessRemindersRoute: typeof ApiPublicHooksProcessRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rejestracja': {
      id: '/rejestracja'
      path: '/rejestracja'
      fullPath: '/rejestracja'
      preLoaderRoute: typeof RejestracjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grafik': {
      id: '/grafik'
      path: '/grafik'
      fullPath: '/grafik'
      preLoaderRoute: typeof GrafikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/moje-rezerwacje': {
      id: '/_authenticated/moje-rezerwacje'
      path: '/moje-rezerwacje'
      fullPath: '/moje-rezerwacje'
      preLoaderRoute: typeof AuthenticatedMojeRezerwacjeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/konto': {
      id: '/_authenticated/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof AuthenticatedKontoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/process-reminders': {
      id: '/api/public/hooks/process-reminders'
      path: '/api/public/hooks/process-reminders'
      fullPath: '/api/public/hooks/process-reminders'
      preLoaderRoute: typeof ApiPublicHooksProcessRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedKontoRoute: typeof AuthenticatedKontoRoute
  AuthenticatedMojeRezerwacjeRoute: typeof AuthenticatedMojeRezerwacjeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedKontoRoute: AuthenticatedKontoRoute,
  AuthenticatedMojeRezerwacjeRoute: AuthenticatedMojeRezerwacjeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GrafikRoute: GrafikRoute,
  LoginRoute: LoginRoute,
  RejestracjaRoute: RejestracjaRoute,
  ApiPublicHooksProcessRemindersRoute: ApiPublicHooksProcessRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
