REVOKE EXECUTE ON FUNCTION public.delete_email(text, bigint) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.enqueue_email(text, jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.read_email_batch(text, integer, integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.move_to_dlq(text, text, bigint, jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.email_queue_dispatch() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.find_user_id_by_email(text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.book_with_package(uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cancel_booking(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.my_active_packages() FROM anon;
REVOKE EXECUTE ON FUNCTION public.waitlist_position(uuid) FROM anon;